DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS bunnies;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(30) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL
);

CREATE TABLE bunnies (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  is_adopted BOOLEAN NOT NULL,
  description TEXT,
  img_url VARCHAR(60) NOT NULL,
  user_id INTEGER REFERENCES users(id)
);
